[package]
name = "rust_opengl"
version = "0.1.0"
authors = ["jay.yabsley"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.31.0"

[build]
build = "build.rs"